sudo: required
dist: trusty
language: generic

env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros
    - ROS_DISTRO="indigo" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
